parameters:
    commonmark.configuration:
        allow_unsafe_links: false
        html_input: escape
        max_nesting_level: 25
        renderer:
            soft_break: "<br/>\r\n"
    commonmark.allowed_schemes: [http, https]

services:
    _defaults:
        autowire: true
        public: false

    League\CommonMark\Extension\Autolink\UrlAutolinkParser:
        arguments:
            $allowedProtocols: "%commonmark.allowed_schemes%"
    League\CommonMark\Extension\CommonMark\CommonMarkCoreExtension: ~
    