framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      sync: 'sync://'
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          delay: 30000
          multiplier: 2
          max_delay: 0
      async_ap:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        retry_strategy:
          max_retries: 3
          delay: 30000
          multiplier: 2
          max_delay: 0
      failed: 'doctrine://default?queue_name=failed'

    routing:
      # Route your messages to the transports
      App\Message\Contracts\AsyncMessageInterface: async
      App\Message\Contracts\AsyncApMessageInterface: async_ap
