version: "3.9"

services:
  www:
    build: .
    image: kbin
    restart: unless-stopped
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    ports:
      - 80:80
    volumes:
      - ./caddy_config:/config
      - ./caddy_data:/data
    environment:
      - SERVER_NAME=:80  # determine where the web server binds
      - PHP_FASTCGI_HOST=php:9000  # forward to php container via this url
      - MERCURE_PUBLISHER_JWT_KEY=$MERCURE_JWT_SECRET
      - MERCURE_SUBSCRIBER_JWT_KEY=$MERCURE_JWT_SECRET
    depends_on:
      - php

  php:
    build: .
    image: kbin
    restart: unless-stopped
    command: php-fpm
    volumes:
      - ./media:/var/www/kbin/public/media
    environment:
      - PHP_FASTCGI_HOST=php:9000
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger:
    build: .
    image: kbin
    restart: unless-stopped
    command: bin/console messenger:consume async --time-limit=3600
    environment:
      - PHP_FASTCGI_HOST=php:9000
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  messenger_ap:
    build: .
    image: kbin
    restart: unless-stopped
    command: bin/console messenger:consume async_ap --time-limit=3600
    environment:
      - PHP_FASTCGI_HOST=php:9000
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    volumes:
      - ./redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kbin
      - POSTGRES_USER=kbin

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=kbin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://www:80
  # nginx:
  #  image: nginx
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
