version: "3.9"

services:
  kbin:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - ./media:/var/www/kbin/public/media
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq
      - mercure

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kbin
      - POSTGRES_USER=kbin

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=kbin
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      - SERVER_NAME=:80
      - MERCURE_TRANSPORT_URL=bolt:///data/mercure.db
      - MERCURE_PUBLISHER_JWT_KEY=${MERCURE_JWT_SECRET}
      - MERCURE_SUBSCRIBER_JWT_KEY=${MERCURE_JWT_SECRET}
      - MERCURE_EXTRA_DIRECTIVES= |-
          anonymous
          subscriptions
    volumes:
      - ./mercure_config:/config
      - ./mercure_data:/data

  # Add your favorite reverse proxy (e.g nginx) which accept incoming HTTPS
  # traffic and forward to http://kbin:9001
  # nginx:
  #  image: nginx
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
