ajax_fetch_title:
  controller: App\Controller\AjaxController::fetchTitle
  defaults: { _format: json }
  path: /ajax/fetch_title
  methods: [POST]

ajax_fetch_embed:
  controller: App\Controller\AjaxController::fetchEmbed
  defaults: { _format: json }
  path: /ajax/fetch_embed
  methods: [GET]

ajax_fetch_post_comments:
  controller: App\Controller\AjaxController::fetchPostComments
  defaults: { _format: json }
  path: /ajax/fetch_post_comments/{id}
  methods: [GET]
