ajax_fetch_title:
  controller: App\Controller\AjaxController::fetchTitle
  defaults: { _format: json }
  path: /ajax/fetch_title
  methods: [POST]

ajax_fetch_embed:
  controller: App\Controller\AjaxController::fetchEmbed
  defaults: { _format: json }
  path: /ajax/fetch_embed/{id}
  methods: [GET]
