entry_comment_create:
  controller: App\Controller\EntryCommentController::create
  defaults: { parent_comment_id: null }
  path: /m/{magazine_name}/t/{entry_id}/komentarz/{parent_comment_id}
  methods: [ POST ]

entry_comment_reply:
  controller: App\Controller\EntryCommentController::reply
  path: /m/{magazine_name}/t/{entry_id}/komentarz/{comment_id}/odpowiedz
  methods: [ GET, POST ]

entry_comment_edit:
  controller: App\Controller\EntryCommentController::edit
  path: /m/{magazine_name}/t/{entry_id}/komentarz/{comment_id}/edytuj
  methods: [ GET, POST ]

entry_comment_purge:
  controller: App\Controller\EntryCommentController::purge
  path: /m/{magazine_name}/t/{entry_id}/komentarz/{comment_id}/purge
  methods: [ GET, POST ]

entry_comment_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\EntryComment }
  path: /ecv/{id}/{choice}
  methods: [POST]

entry_comments:
  controller: App\Controller\EntryCommentController::front
  defaults: { sortBy: ~ }
  path: /komentarze/{sortBy}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

subscribed_comments:
  controller: App\Controller\EntryCommentController::front
  defaults: { sortBy: ~ }
  path: /sub/komentarze/{sortBy}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

magazine_comments:
  controller: App\Controller\EntryCommentController::front
  defaults: { sortBy: ~ }
  path: /m/{name}/komentarze/{sortBy}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }
