comment_create:
  controller: App\Controller\CommentController::createComment
  defaults: { parent_comment_id: null }
  path: /m/{magazine_name}/t/{entry_id}/komentarz/{parent_comment_id}
  methods: [ POST, GET ]

comment_edit:
  controller: App\Controller\CommentController::editComment
  path: /m/{magazine_name}/t/{entry_id}/komentarz/{comment_id}/edytuj
  methods: [ GET, POST ]

