entry:
  controller: App\Controller\EntryController::front
  path: /m/{magazine_name}/t/{entry_id}
  methods: [ GET ]

entry_create:
  controller: App\Controller\EntryController::createEntry
  defaults: { name: null }
  path: /nowaTresc/{name}
  methods: [ GET, POST ]
