entry:
  controller: App\Controller\EntryController::front
  path: /m/{magazine_name}/t/{entry_id}
  methods: [ GET ]

entry_create:
  controller: App\Controller\EntryController::createEntry
  defaults: { type: null }
  path: /nowaTresc/{type}
  methods: [ GET, POST ]

entry_edit:
  controller: App\Controller\EntryController::editEntry
  path: /m/{magazine_name}/t/{entry_id}/edytuj
  methods: [ GET, POST ]

entry_purge:
  controller: App\Controller\EntryController::purgeEntry
  path: /m/{magazine_name}/t/{entry_id}/purge
  methods: [ POST ]

entry_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\Entry }
  path: /ev/{id}/{choice}
  methods: [POST]
