front:
  controller: App\Controller\FrontController::front
  defaults: { sortBy: ~ }
  path: /{sortBy}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

subscribed:
  controller: App\Controller\FrontController::subscribed
  defaults: { sortBy: ~ }
  path: /sub/{sortBy}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }
