magazine_create:
  controller: App\Controller\MagazineController::create
  path: /nowyMagazyn
  methods: [ GET, POST ]

magazine_delete:
  controller: App\Controller\MagazineController::delete
  path: /m/{name}/delete
  methods: [ POST ]

magazine_purge:
  controller: App\Controller\MagazineController::purge
  path: /m/{name}/purge
  methods: [ POST ]

magazine_list_all:
  controller: App\Controller\MagazineController::listAll
  path: /magazyny
  methods: [ GET ]

magazine_moderators:
  controller: App\Controller\MagazineController::moderators
  path: /m/{name}/moderatorzy
  methods: [ GET ]

magazine_modlog:
  controller: App\Controller\MagazineController::modlog
  path: /m/{name}/modlog
  methods: [ GET ]

magazine_subscribe:
  controller: App\Controller\MagazineController::subscribe
  path: /m/{name}/subscribe
  methods: [ POST ]

magazine_unsubscribe:
  controller: App\Controller\MagazineController::unsubscribe
  path: /m/{name}/unsubscribe
  methods: [ POST ]

magazine_block:
  controller: App\Controller\MagazineController::block
  path: /m/{name}/block
  methods: [ POST ]

magazine_unblock:
  controller: App\Controller\MagazineController::unblock
  path: /m/{name}/unblock
  methods: [ POST ]
