messages_front:
  controller: App\Controller\Message\MessageThreadListController
  path: /profil/wiadomości
  methods: [ GET ]

messages_single:
  controller: App\Controller\Message\MessageThreadController
  path: /profil/wiadomości/{id}
  methods: [ GET, POST ]

messages_create:
  controller: App\Controller\Message\MessageCreateThreadController
  path: /u/{username}/wiadomość
  methods: [ GET, POST ]
