messages_front:
  controller: App\Controller\Message\MessageThreadListController
  path:
    en: /profile/messages
    pl: /profil/wiadomości
  methods: [ GET ]

messages_single:
  controller: App\Controller\Message\MessageThreadController
  path:
    en: /profile/messages/{id}
    pl: /profil/wiadomości/{id}
  methods: [ GET, POST ]

messages_create:
  controller: App\Controller\Message\MessageCreateThreadController
  path:
    en: /u/{username}/message
    pl: /u/{username}/wiadomość
  methods: [ GET, POST ]
