page_contact:
  controller: App\Controller\ContactController
  path: /kontakt
  methods: [ GET, POST ]

page_faq:
  controller: App\Controller\FaqController
  path: /faq
  methods: [ GET ]

page_privacy_policy:
  controller: App\Controller\PrivacyPolicyController
  path: /polityka-prywatnosci
  methods: [ GET ]

page_terms:
  controller: App\Controller\TermsController
  path: /regulamin
  methods: [ GET ]

award_list_all:
  controller: App\Controller\AwardListController
  defaults: { category: ~ }
  path: /odznaczenia/{category}
  methods: [ GET ]

stats:
  controller: App\Controller\StatsController
  defaults: { statsType: ~, statsPeriod: ~ }
  path: /statystyki/{statsType}/{statsPeriod}
  methods: [ GET ]

ranking:
  controller: App\Controller\RankingController
  path: /ranking
  methods: [ GET ]
