post_comment_create:
  controller: App\Controller\Post\Comment\CommentCreateController
  defaults: { slug: -, parent_comment_id: null }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/reply/{parent_comment_id}
    pl: /m/{magazine_name}/w/{post_id}/{slug}/odpowiedź/{parent_comment_id}
  methods: [ GET, POST ]

post_comment_edit:
  controller: App\Controller\Post\Comment\CommentEditController
  defaults: { slug: -, }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/edit
    pl: /m/{magazine_name}/w/{post_id}/{slug}/odpowiedź/{comment_id}/edytuj
  methods: [ GET, POST ]

post_comment_delete:
  controller: App\Controller\Post\Comment\CommentDeleteController::delete
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/delete
  methods: [ POST ]

post_comment_restore:
  controller: App\Controller\Post\Comment\CommentDeleteController::restore
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/restore
  methods: [ POST ]

post_comment_purge:
  controller: App\Controller\Post\Comment\CommentDeleteController::purge
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/purge
  methods: [ POST ]

post_comment_image_delete:
  controller: App\Controller\Post\Comment\CommentDeleteImageController
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/delete_image
  methods: [ POST ]

post_comment_voters:
  controller: App\Controller\Post\Comment\PostCommentVotersController
  defaults: { slug: -, }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/votes
    pl: /m/{magazine_name}/w/{post_id}/{slug}/odpowiedź/{comment_id}/głosy
  methods: [ GET ]

post_comment_favourites:
  controller: App\Controller\Post\Comment\PostCommentFavouriteController
  defaults: { slug: -, }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/reply/{comment_id}/favourites
    pl: /m/{magazine_name}/w/{post_id}/{slug}/odpowiedź/{comment_id}/ulubione
  methods: [ GET ]

post_comment_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcv/{id}/{choice}
  methods: [ POST ]

post_comment_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcr/{id}
  methods: [ GET, POST ]

post_comment_favourite:
  controller: App\Controller\FavouriteController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcf/{id}
  methods: [ POST ]

posts_front:
  controller: App\Controller\Post\PostFrontController::front
  defaults: { sortBy: hot, time: ~ }
  path:
    en: /microblog/{sortBy}/{time}
    pl: /wpisy/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

posts_subscribed:
  controller: App\Controller\Post\PostFrontController::subscribed
  defaults: { sortBy: hot, time: ~ }
  path:
    en: /sub/microblog/{sortBy}/{time}
    pl: /sub/wpisy/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

posts_moderated:
  controller: App\Controller\Post\PostFrontController::moderated
  defaults: { sortBy: hot, time: ~ }
  path:
    en: /mod/microblog/{sortBy}/{time}
    pl: /mod/wpisy/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

posts_favourite:
  controller: App\Controller\Post\PostFrontController::favourite
  defaults: { sortBy: hot, time: ~ }
  path:
    en: /fav/microblog/{sortBy}/{time}
    pl: /fav/wpisy/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

magazine_posts:
  controller: App\Controller\Post\PostFrontController::magazine
  defaults: { sortBy: hot, time: ~ }
  path:
    en: /m/{name}/microblog/{sortBy}/{time}
    pl: /m/{name}/wpisy/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

post_voters:
  controller: App\Controller\Post\PostVotersController
  defaults: { slug: -, sortBy: hot }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/votes
    pl: /m/{magazine_name}/w/{post_id}/{slug}/głosy
  methods: [ GET ]

post_favourites:
  controller: App\Controller\Post\PostFavouriteController
  defaults: { slug: -, sortBy: hot }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/favourites
    pl: /m/{magazine_name}/w/{post_id}/{slug}/ulubione
  methods: [ GET ]

post_single:
  controller: App\Controller\Post\PostSingleController
  defaults: { slug: -, sortBy: hot }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/{sortBy}
    pl: /m/{magazine_name}/w/{post_id}/{slug}/{sortBy}
  methods: [ GET ]

post_create:
  controller: App\Controller\Post\PostCreateController
  path: /microblog/create
  methods: [ GET, POST ]

post_edit:
  controller: App\Controller\Post\PostEditController
  defaults: { slug: -, }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/edit
    pl: /m/{magazine_name}/w/{post_id}/{slug}/edytuj
  methods: [ GET, POST ]

post_moderate:
  controller: App\Controller\Post\PostModerateController
  defaults: { slug: -, }
  path:
    en: /m/{magazine_name}/p/{post_id}/{slug}/moderate
    pl: /m/{magazine_name}/w/{post_id}/{slug}/moderuj
  methods: [ GET, POST ]

post_delete:
  controller: App\Controller\Post\PostDeleteController::delete
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/delete
  methods: [ POST ]

post_restore:
  controller: App\Controller\Post\PostDeleteController::restore
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/restore
  methods: [ POST ]

post_purge:
  controller: App\Controller\Post\PostDeleteController::purge
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/purge
  methods: [ POST ]

post_image_delete:
  controller: App\Controller\Post\PostDeleteImageController
  defaults: { slug: -, }
  path: /m/{magazine_name}/p/{post_id}/{slug}/delete_image
  methods: [ POST ]

post_change_magazine:
  controller: App\Controller\Post\PostChangeMagazineController
  defaults: { slug: - }
  path: /m/{magazine_name}/p/{post_id}/{slug}/change_magazine
  methods: [ POST ]

post_change_adult:
  controller: App\Controller\Post\PostChangeAdultController
  defaults: { slug: - }
  path: /m/{magazine_name}/p/{post_id}/{slug}/change_adult
  methods: [ POST ]

post_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\Post }
  path: /pv/{id}/{choice}
  methods: [ POST ]

post_report:
  controller: App\Controller\ReportController
  defaults: { entityClass: App\Entity\Post }
  path: /pr/{id}
  methods: [ GET, POST ]

post_favourite:
  controller: App\Controller\FavouriteController
  defaults: { entityClass: App\Entity\Post }
  path: /pf/{id}
  methods: [ POST ]
