post_comment_create:
  controller: App\Controller\PostCommentController::create
  defaults: { parent_comment_id: null }
  path: /m/{magazine_name}/w/{post_id}/komentarz/{parent_comment_id}
  methods: [ GET, POST ]

post_comment_edit:
  controller: App\Controller\PostCommentController::edit
  path: /m/{magazine_name}/w/{post_id}/komentarz/{comment_id}/edytuj
  methods: [ GET, POST ]

post_comment_vote:
  controller: App\Controller\VoteController
  defaults: { entityClass: App\Entity\PostComment }
  path: /pcv/{id}/{choice}
  methods: [POST]
