post_comment_create:
  controller: App\Controller\PostCommentController::create
  defaults: { parent_comment_id: null }
  path: /m/{magazine_name}/w/{post_id}/komentarz/{parent_comment_id}
  methods: [ GET, POST ]
