app_register:
  controller: App\Controller\SecurityController::register
  path: /zarejestruj
  methods: [ GET, POST ]

app_verify_email:
  controller: App\Controller\SecurityController::verifyUserEmail
  path: /zweryfikuj/email
  methods: [ GET ]

app_login:
  controller: App\Controller\SecurityController::login
  path: /zaloguj
  methods: [ GET, POST ]

app_logout:
  controller: App\Controller\SecurityController::logout
  path: /wyloguj
  methods: [ GET ]
