tag_overall:
  controller: App\Controller\Tag\OverallController
  path: /tag/{name}
  methods: [GET]

tag_front:
  controller: App\Controller\Tag\FrontController
  defaults: { sortBy: hot, time: ~ }
  path:
    en: tag/{name}/threads/{sortBy}/{time}
    pl: tag/{name}/treści/{sortBy}/{time}
  methods: [ GET ]
  requirements: { sortBy: "%front_sort_options%" }

tag_entry_comments_front:
  controller: App\Controller\Tag\CommentFrontController
  defaults: { sortBy: hot, time: ~ }
  path:
    en: tag/{name}/comments/{sortBy}/{time}
    pl: tag/{name}/komentarze/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }

tag_posts_front:
  controller: App\Controller\Tag\PostFrontController
  defaults: { sortBy: hot, time: ~ }
  path:
    en: tag/{name}/posts/{sortBy}/{time}
    pl: tag/{name}/wpisy/{sortBy}/{time}
  methods: [GET]
  requirements: { sortBy: "%front_sort_options%" }
