user:
  controller: App\Controller\UserController::front
  path: /u/{username}
  methods: [ GET ]

user_entries:
  controller: App\Controller\UserController::entries
  path: /u/{username}/tresci
  methods: [ GET ]

user_entry_comments:
  controller: App\Controller\UserController::comments
  path: /u/{username}/komentarze
  methods: [ GET ]

user_follow:
  controller: App\Controller\UserController::follow
  path: /u/{username}/follow
  methods: [ POST ]

user_unfollow:
  controller: App\Controller\UserController::unfollow
  path: /u/{username}/unfollow
  methods: [ POST ]

user_block:
  controller: App\Controller\UserController::block
  path: /u/{username}/block
  methods: [ POST ]

user_unblock:
  controller: App\Controller\UserController::unblock
  path: /u/{username}/unblock
  methods: [ POST ]

user_profile_front:
  controller: App\Controller\UserController::profile
  path: /profil
  methods: [ GET ]

user_profile_notifications:
  controller: App\Controller\UserController::profile
  path: /profil/notyfikacje
  methods: [ GET ]

user_profile_messages:
  controller: App\Controller\UserController::profile
  path: /profil/wiadomosci
  methods: [ GET ]

user_profile_settings:
  controller: App\Controller\UserController::profile
  path: /profil/ustawienia
  methods: [ GET ]

user_profile_edit:
  controller: App\Controller\UserController::edit
  path: /profil/edytuj
  methods: [ GET, POST ]
