

user_overview:
  controller: App\Controller\User\UserFrontController::front
  path: /u/{username}
  methods: [ GET ]

user_entries:
  controller: App\Controller\User\UserFrontController::entries
  path: /u/{username}/treści
  methods: [ GET ]

user_comments:
  controller: App\Controller\User\UserFrontController::comments
  path: /u/{username}/komentarze
  methods: [ GET ]

user_posts:
  controller: App\Controller\User\UserFrontController::posts
  path: /u/{username}/wpisy
  methods: [ GET ]

user_replies:
  controller: App\Controller\User\UserFrontController::replies
  path: /u/{username}/odpowiedzi
  methods: [ GET ]

user_boosts:
  controller: App\Controller\User\UserFrontController::boosts
  path: /u/{username}/boosts
  methods: [ GET ]

user_moderated:
  controller: App\Controller\User\UserFrontController::moderated
  path: /u/{username}/moderowane
  methods: [ GET ]

user_subscriptions:
  controller: App\Controller\User\UserFrontController::subscriptions
  path: /u/{username}/subskrypcje
  methods: [ GET ]

user_followers:
  controller: App\Controller\User\UserFrontController::followers
  path: /u/{username}/obserwujący
  methods: [ GET ]

user_following:
  controller: App\Controller\User\UserFrontController::following
  path: /u/{username}/obserwowani
  methods: [ GET ]

user_follow:
  controller: App\Controller\User\UserFollowController::follow
  path: /u/{username}/follow
  methods: [ POST ]

user_awards:
  controller: App\Controller\User\UserAwardController
  defaults: { category: ~ }
  path: /u/{username}/odznaczenia/{awardsCategory}
  methods: [ GET ]

user_reputation:
  controller: App\Controller\User\UserReputationController
  defaults: { reputationType: ~ }
  path: /u/{username}/reputacja/{reputationType}
  methods: [ GET ]

user_unfollow:
  controller: App\Controller\User\UserFollowController::unfollow
  path: /u/{username}/unfollow
  methods: [ POST ]

user_block:
  controller: App\Controller\User\UserBlockController::block
  path: /u/{username}/block
  methods: [ POST ]

user_unblock:
  controller: App\Controller\User\UserBlockController::unblock
  path: /u/{username}/unblock
  methods: [ POST ]

user_purge:
  controller: App\Controller\User\UserDeleteController::purge
  path: /u/{username}/purge
  methods: [ POST ]

user_delete:
  controller: App\Controller\User\UserDeleteController::delete
  path: /u/{username}/delete
  methods: [ POST ]

user_delete_request:
  controller: App\Controller\User\UserDeleteRequestController
  path: /u/{username}/delete_request
  methods: [ POST ]

user_ban:
  controller: App\Controller\User\UserBanController::ban
  path: /u/{username}/ban
  methods: [ POST ]

user_unban:
  controller: App\Controller\User\UserBanController::unban
  path: /u/{username}/unban
  methods: [ POST ]

user_note:
  controller: App\Controller\User\UserNoteController
  path: /u/{username}/note
  methods: [ POST ]

notifications_front:
  controller: App\Controller\User\Profile\UserNotificationController::notifications
  path: /ustawienia/notyfikacje
  methods: [ GET ]

notifications_read:
  controller: App\Controller\User\Profile\UserNotificationController::read
  path: /settings/notifications/read
  methods: [ POST ]

notifications_clear:
  controller: App\Controller\User\Profile\UserNotificationController::clear
  path: /settings/notifications/clear
  methods: [ POST ]

user_settings_reports:
  controller: App\Controller\User\Profile\UserReportsController
  path: /ustawienia/zgłoszenia
  methods: [ GET ]

user_settings_magazine_blocks:
  controller: App\Controller\User\Profile\UserBlockController::magazines
  path: /ustawienia/blokady/magazyny
  methods: [ GET ]

user_settings_domain_blocks:
  controller: App\Controller\User\Profile\UserBlockController::domains
  path: /ustawienia/blokady/domeny
  methods: [ GET ]

user_settings_user_blocks:
  controller: App\Controller\User\Profile\UserBlockController::users
  path: /ustawienia/blokady/ludzie
  methods: [ GET ]

user_settings_magazine_subscriptions:
  controller: App\Controller\User\Profile\UserSubController::magazines
  path: /ustawienia/subskrypcje/magazyny
  methods: [ GET ]

user_settings_domain_subscriptions:
  controller: App\Controller\User\Profile\UserSubController::domains
  path: /ustawienia/subskrypcje/domeny
  methods: [ GET ]

user_settings_user_subscriptions:
  controller: App\Controller\User\Profile\UserSubController::users
  path: /ustawienia/subskrypcje/ludzie
  methods: [ GET ]

user_settings_tips:
  controller: App\Controller\User\Profile\UserTipController
  path: /ustawienia/ada
  methods: [ GET, POST ]

user_settings_general:
  controller: App\Controller\User\Profile\UserSettingController
  path: /ustawienia/ogólne
  methods: [ GET, POST ]

user_settings_profile:
  controller: App\Controller\User\Profile\UserEditController::general
  path: /ustawienia/profil
  methods: [ GET, POST ]

user_settings_email:
  controller: App\Controller\User\Profile\UserEditController::email
  path: /ustawienia/email
  methods: [ GET, POST ]

user_settings_password:
  controller: App\Controller\User\Profile\UserEditController::password
  path: /ustawienia/hasło
  methods: [ GET, POST ]

user_settings_avatar_delete:
  controller: App\Controller\User\UserAvatarDeleteController
  path: /settings/edit/delete_avatar
  methods: [ POST ]

user_settings_cover_delete:
  controller: App\Controller\User\UserCoverDeleteController
  path: /settings/edit/delete_cover
  methods: [ POST ]

user_settings_toggle_theme:
  controller: App\Controller\User\UserThemeController
  path: /ustawienia/edytuj/wyglad
  methods: [ GET, POST ]

user_settings_stats:
  controller: App\Controller\User\Profile\UserStatsController
  defaults: { statsType: content, statsPeriod: ~ }
  path: /ustawienia/{statsType}/{statsPeriod}
  methods: [ GET ]

theme_settings:
  controller: App\Controller\User\ThemeSettingsController
  path: /settings/theme/{key}/{value}
  methods: [ GET ]