user:
  controller: App\Controller\UserController::front
  path: /u/{username}
  methods: [ GET ]

user_entries:
  controller: App\Controller\UserController::entries
  path: /u/{username}/tresci
  methods: [ GET ]

user_entry_comments:
  controller: App\Controller\UserController::comments
  path: /u/{username}/komentarze
  methods: [ GET ]
