parameters:
    html5_validation: false
    front_sort_options: wazne|wschodzace|aktywne|najnowsze|komentowane
    front_time_options: 6h|12h|1d|1w|1m|1y|wszystko|∞
    number_regex: '[1-9][0-9]{0,17}'
    username_regex: '\w{2,25}|!deleted\d+'
    uploads_dir_name: 'media'
    uploads_base_url: '%env(SITE_BASE_URL)%/%uploads_dir_name%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $html5Validation: '%html5_validation%'
            $uploadedAssetsBaseUrl: '%uploads_base_url%'

    _instanceof:
        League\CommonMark\Inline\Parser\InlineParserInterface:
            tags: [commonmark.inline_parser]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Markdown\Factory\EnvironmentFactory:
        $container: !service_locator
            League\CommonMark\ConfigurableEnvironmentInterface: '@League\CommonMark\ConfigurableEnvironmentInterface'
