parameters:
    html5_validation: false
    front_sort_options: wazne|najnowsze|wschodzace|komentowane

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $html5Validation: '%html5_validation%'

    _instanceof:
        League\CommonMark\Inline\Parser\InlineParserInterface:
            tags: [commonmark.inline_parser]

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Markdown\Factory\EnvironmentFactory:
        $container: !service_locator
            League\CommonMark\ConfigurableEnvironmentInterface: '@League\CommonMark\ConfigurableEnvironmentInterface'
