parameters:
    html5_validation: false
services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $html5Validation: '%html5_validation%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
