version: "3.9"

services:
  kbin:
    build:
      context: .
      target: runner
    restart: unless-stopped
    ports:
      - 9001:9001
    volumes:
      - ./.env:/var/www/kbin/.env
      - ./media:/var/www/kbin/public/media
    depends_on:
      - redis
      - db

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./redis:/data
    command: /bin/sh -c "redis-server --requirepass $${REDIS_PASSWORD}"
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  db:
    image: postgres:13-bullseye
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql
    environment:
      - POSTGRES_DB=kbin
      - POSTGRES_USER=kbin

  # Reverse proxy in front of the kbin container (Optional)
  # nginx:
  #  image: nginx
  #  ports:
  #    - 443:443
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
